### ISSUE TITLE
Running setup_data.py

### ISSUE THREAD

**Issue by zkrischer** [csiro-robotics/WildScenes#10]
I've installed the dataset following the guide from the CSIRO website and am attempting to run setup_data.py script. However running it the first time fails resulting in the following error:

AssertionError: ERROR: /home/zeev/Documents/Datasets/WildScenes/WildScenes3d/K-03/Hist_Labels/1639438280.765902736.hist

Attempting to run the script again without the --override argument makes it appear as if it works when in fact it just does not try again as the folder structure has been created.

After doing some looking it appears as if the train/test/val csv's have a path definition that does not match the one in the dataset. Those csv's assume that the hists folder is called Hist_Labels (when it is in fact called Hists) and that the files within are .hist when they are .csv

Is it better to change the csv's that are defining the path or the actual dataset folders/items?

**Comment by StephenHausler** [comment]
Hi @zkrischer 
Thanks for finding this issue, as an interim solution you could change either for now, however what I'll do is prepare a fix soon to the code - the names in the actual dataset are correct, looks like a code bug which resulted from an old naming convention we had used earlier in the project. I'll leave this open and fix the bug very soon.

**Comment by StephenHausler** [comment]
This issue should be fixed now, closing this issue, feel free to reopen if you find any more bugs.
