### ISSUE TITLE
Lidar to base_link ( IMU ) external parameter calibration?

### ISSUE THREAD

**Issue by phoenixGG** [csiro-robotics/WildScenes#11]
Hello, I am very interested in the WildScenes dataset. In the WildScenes2d folder, I found the camera_calibration.yaml file, which contains the extrinsic parameters between the LiDAR and the camera. Since the paper mentions that the LiDAR is installed at an angle, I would like to ask if there are any relative extrinsic parameters between the LiDAR and the base_link coordinate system. The base_link coordinate system could be defined as having the X-axis pointing forward, the Y-axis to the left, and the Z-axis pointing upward. Alternatively, the base_link coordinate system could be assumed to align with the orientation of the IMU coordinate system.

**Comment by StephenHausler** [comment]
Hi, in our dataset essentially what we refer to as the 3D coordinate frame is the same as the base_link. The camera extrinsics we provide are from the camera frame to the base_link already. Our 3D points are already converted from the LiDAR coordinate frame (as seen in Fig 3 in our paper) into the base frame. The base frame is the same frame as the IMU as well. Therefore there has been no need to release the transform from the LiDAR coordinate to the base_link as it won't match the 3D point data we release which has already been post-processed to be in the base_link coordinate frame. Hope this answers your query.
