### ISSUE TITLE
calibration parameters

### ISSUE THREAD

**Issue by zwk0901** [csiro-robotics/WildScenes#2]
Hello, your data on unstructured scenes is very comprehensive, I wonder if you provide external calibration parameters on Lidar and camera.

**Comment by StephenHausler** [comment]
Hi @zwk0901, I think we already include the calibration parameters that you are looking for? In the WildScenes2d folder there are files named "camera_calibration.yaml" which contain intrinsics and extrinsics parameters. The extrinsics are the transforms between the lidar coordinate frame and the camera. Is this what you are looking for?

**Comment by StephenHausler** [comment]
Closing this issue, feel free to re-open if you have further questions.
