### ISSUE TITLE
Labels appear twice with the same color

### ISSUE THREAD

**Issue by BngZhWU** [csiro-robotics/WildScenes#5]
In WildScenes/wildscenes/tools/utils2d.py, 
different labels appear twice with the same color, and these two labels are not merged to each other.
![屏幕截图 2024-07-12 061655](https://github.com/user-attachments/assets/1f948bb6-d49f-4aa0-a7bd-65d9500e56d0)

**Comment by StephenHausler** [comment]
Hi, thanks for finding this error in our palette. Thankfully, as this class is not used during benchmarking this error won't affect any of the benchmark results, however I'll still make this fix to the palette. I'm currently preparing the next iteration of the WildScenes codebase and will fix this issue in my update. I'll close this issue after releasing the next version.

**Comment by StephenHausler** [comment]
This error should be resolved now, will close this issue. Feel free to re-open if you find that the bug is still present or other bugs arise.
