### ISSUE TITLE
open3d version

### ISSUE THREAD

**Issue by SWKWS** [csiro-robotics/WildScenes#6]
I noticed a discrepancy between the specified versions of open3d in the project documentation:

- [installation.md](https://github.com/csiro-robotics/WildScenes/blob/main/installation.md#:~:text=pip%20install%20open3d%3D%3D0.1.8) specifies `open3d==0.1.8` 
- [requirements.txt](https://github.com/csiro-robotics/WildScenes/blob/main/requirements.txt) specifies `open3d=0.18.0=pypi_0`.

It appears that version 0.1.8 does not exist for open3d. This might be a typo in installation.md. Could you please clarify or correct the version number?

Thank you!

**Comment by StephenHausler** [comment]
Hi, thanks for spotting this error, this is definitely a typo. I'm currently preparing a new version of the WildScenes codebase, I'll make this correction in the new version. I'll close this issue after pushing the new iteration of this codebase.

**Comment by StephenHausler** [comment]
This issue should be resolved now, closing this issue.
